[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = ['markdown', 'tsx', 'typescript', 'csv', 'dockerfile']
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

# autopairは邪魔かも
# [[plugins]]
# repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'kana/vim-operator-user'

# formatterは、googleに変更する
#[[plugins]]
#repo = 'rhysd/vim-clang-format'
# autoformattも一旦外してみる
# [[plugins]]
# repo = 'Chiel92/vim-autoformat'

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"
hook_add = 
'''
    set statusline+=%{fugitive#statusline()}
'''

[[plugins]]
repo = 'mhartington/oceanic-next'
hook_add = '''
colorscheme OceanicNext
'''


#coc系を入れてみる
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merge = 0
hook_add = '''
source ~/.config/nvim/coc.vim
'''

[[plugins]]
repo = '/usr/local/opt/fzf'

#fzf
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'


## 重たそうだから一旦使わない
## [[plugins]]
## repo = 'unblevable/quick-scope'

